{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintBing.
--   Generated by the BNF converter.

module PrintBing where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsBing

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsBing.Ident where
  prt _ (AbsBing.Ident i) = doc $ showString i

instance Print AbsBing.Program where
  prt i = \case
    AbsBing.Program topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print AbsBing.TopDef where
  prt i = \case
    AbsBing.FnDef type_ id_ params block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 params, doc (showString ")"), prt 0 block])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsBing.TopDef] where
  prt = prtList

instance Print AbsBing.Param where
  prt i = \case
    AbsBing.Param type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsBing.Param] where
  prt = prtList

instance Print AbsBing.Block where
  prt i = \case
    AbsBing.Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsBing.Stmt] where
  prt = prtList

instance Print AbsBing.Stmt where
  prt i = \case
    AbsBing.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    AbsBing.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    AbsBing.Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    AbsBing.FDecl topdef -> prPrec i 0 (concatD [prt 0 topdef])
    AbsBing.CDecl type_ items -> prPrec i 0 (concatD [doc (showString "const"), prt 0 type_, prt 0 items, doc (showString ";")])
    AbsBing.Ass id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsBing.Incr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    AbsBing.Decr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    AbsBing.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsBing.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsBing.While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsBing.For id_ expr1 expr2 stmt -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 id_, doc (showString "="), prt 0 expr1, doc (showString "to"), prt 0 expr2, doc (showString ")"), prt 0 stmt])
    AbsBing.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    AbsBing.Break -> prPrec i 0 (concatD [doc (showString "break"), doc (showString ";")])
    AbsBing.Continue -> prPrec i 0 (concatD [doc (showString "continue"), doc (showString ";")])
    AbsBing.Println expr -> prPrec i 0 (concatD [doc (showString "println"), doc (showString "("), prt 0 expr, doc (showString ")")])
    AbsBing.Print expr -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 expr, doc (showString ")")])
    AbsBing.CondS expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsBing.CondE expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    AbsBing.CondC expr block econd -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block, prt 0 econd])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsBing.Item where
  prt i = \case
    AbsBing.NoInit id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsBing.Init id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsBing.Item] where
  prt = prtList

instance Print AbsBing.ECond where
  prt i = \case
    AbsBing.ECondS expr block -> prPrec i 0 (concatD [doc (showString "elif"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsBing.ECondE expr block1 block2 -> prPrec i 0 (concatD [doc (showString "elif"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    AbsBing.ECondC expr block econd -> prPrec i 0 (concatD [doc (showString "elif"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block, prt 0 econd])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsBing.ECond] where
  prt = prtList

instance Print AbsBing.Type where
  prt i = \case
    AbsBing.Int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsBing.Str -> prPrec i 0 (concatD [doc (showString "string")])
    AbsBing.Bool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsBing.Void -> prPrec i 0 (concatD [doc (showString "void")])
    AbsBing.Fun type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsBing.Type] where
  prt = prtList

instance Print AbsBing.Arg where
  prt i = \case
    AbsBing.VArg expr -> prPrec i 0 (concatD [prt 0 expr])
    AbsBing.PArg id_ -> prPrec i 0 (concatD [doc (showString "&"), prt 0 id_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsBing.Arg] where
  prt = prtList

instance Print AbsBing.Expr where
  prt i = \case
    AbsBing.EVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsBing.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    AbsBing.ELitTrue -> prPrec i 6 (concatD [doc (showString "True")])
    AbsBing.ELitFalse -> prPrec i 6 (concatD [doc (showString "False")])
    AbsBing.EApp id_ args -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")")])
    AbsBing.EString str -> prPrec i 6 (concatD [prt 0 str])
    AbsBing.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsBing.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsBing.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsBing.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsBing.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsBing.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsBing.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsBing.Expr] where
  prt = prtList

instance Print AbsBing.AddOp where
  prt i = \case
    AbsBing.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    AbsBing.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AbsBing.MulOp where
  prt i = \case
    AbsBing.Times -> prPrec i 0 (concatD [doc (showString "*")])
    AbsBing.Div -> prPrec i 0 (concatD [doc (showString "/")])
    AbsBing.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print AbsBing.RelOp where
  prt i = \case
    AbsBing.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    AbsBing.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsBing.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    AbsBing.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsBing.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    AbsBing.NE -> prPrec i 0 (concatD [doc (showString "!=")])

